version: '3'

services:
  my-app:
    container_name: my-app
    hostname: my-app
    #image: ${docker-registry}/my-app:1.0
    image: my-app:1.0
    ports:
     - 3000:3000

  mongodb:
    container_name: mongodb
    hostname: mongodb
    image: mongo
    ports:
     - 27017:27017
    environment:
     - MONGO_INITDB_ROOT_USERNAME=admin                
     - MONGO_INITDB_ROOT_PASSWORD=password

  mongo-express:
    container_name: mongo-express
    hostname: mongo-express
    image: mongo-express
    ports:
     - 8080:8081
    environment:
     - ME_CONFIG_MONGODB_ADMINUSERNAME=admin                
     - ME_CONFIG_MONGODB_ADMINPASSWORD=password
     - ME_CONFIG_MONGODB_SERVER=mongodb